=== Pjb518/FoundryVTT-Level-Up-Official/packs/classFeatures/_classFeaturesSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Class Features Schema",
  "type": "object",
  "default": {},
  "required": [
    "name",
    "type",
    "img",
    "system",
    "effects",
    "flags",
    "_id"
  ],
  "properties": {
    "name": {
      "title": "The name Schema",
      "type": "string",
      "default": "",
      "examples": [
        "A Better Mousetrap",
        "Advanced Grafting",
        "Ancestral Guidance"
      ]
    },
    "type": {
      "title": "The type Schema",
      "type": "string",
      "enum": [
        "feature",
        "object"
      ],
      "examples": [
        "feature",
        "object"
      ]
    },
    "img": {
      "title": "The img Schema",
      "type": "string",
      "default": [
        "icons/svg/item-bag.svg"
      ],
      "examples": [
        "icons/svg/item-bag.svg",
        "icons/weapons/thrown/grenade-round.webp",
        "icons/weapons/thrown/bomb-gas-grey-purple.webp"
      ]
    },
    "system": {
      "title": "The system Schema",
      "type": "object",
      "default": {},
      "required": [
        "ability",
        "actionOptions",
        "activation",
        "attack",
        "area",
        "check",
        "damage",
        "description",
        "duration",
        "healing",
        "proficient",
        "range",
        "save",
        "source",
        "target",
        "uses",
        "featureType"
      ],
      "properties": {
        "ability": {
          "title": "The ability Schema",
          "type": [
            "null",
            "string"
          ],
          "default": "",
          "enum": [
            null,
            "",
            "str",
            "dex",
            "con",
            "int",
            "wis",
            "cha",
            "spellcasting"
          ],
          "examples": [
            null,
            "",
            "str",
            "dex",
            "con",
            "int",
            "wis",
            "cha"
          ]
        },
        "actionOptions": {
          "title": "The actionOptions Schema",
          "type": "array",
          "default": [],
          "items": {
            "title": "A Schema",
            "type": [
              "null",
              "string"
            ],
            "default": "",
            "enum": [
              null,
              "",
              "attack",
              "bonusAction",
              "damage",
              "healing",
              "savingThrow"
            ],
            "examples": [
              "attack",
              "damage",
              "healing",
              "savingThrow"
            ]
          },
          "examples": []
        },
        "activation": {
          "title": "The activation Schema",
          "type": "object",
          "default": {},
          "required": [
            "cost",
            "type",
            "reactionTrigger"
          ],
          "properties": {
            "cost": {
              "title": "The cost Schema",
              "type": [
                "null",
                "string",
                "integer"
              ],
              "default": "",
              "examples": [
                "",
                1
              ]
            },
            "type": {
              "title": "The type Schema",
              "type": "string",
              "default": "",
              "enum": [
                "",
                "action",
                "bonusAction",
                "hour",
                "minute",
                "none",
                "reaction",
                "special"
              ],
              "examples": [
                "",
                "action",
                "special"
              ]
            },
            "reactionTrigger": {
              "title": "The reactionTrigger Schema",
              "type": "string",
              "default": "",
              "examples": [
                ""
              ]
            }
          },
          "examples": []
        },
        "attack": {
          "title": "The attack Schema",
          "type": "object",
          "default": {},
          "required": [
            "bonus",
            "critThreshold",
            "type"
          ],
          "properties": {
            "bonus": {
              "title": "The bonus Schema",
              "type": "string",
              "default": "",
              "examples": [
                ""
              ]
            },
            "critThreshold": {
              "title": "The critThreshold Schema",
              "type": [
                "integer",
                "string"
              ],
              "default": 0,
              "examples": [
                20,
                "20"
              ]
            },
            "type": {
              "title": "The type Schema",
              "type": "string",
              "default": "",
              "examples": [
                "",
                "rangedWeaponAttack"
              ]
            }
          },
          "examples": []
        },
        "area": {
          "title": "The area Schema",
          "type": "object",
          "default": {},
          "properties": {
            "shape": {
              "title": "The shape Schema",
              "type": ["null","string"],
              "default": "",
              "examples": [
                ""
              ]
            },
            "size": {
              "title": "The size Schema",
              "type": "string",
              "default": "",
              "examples": [
                ""
              ]
            }
          },
          "examples": []
        },
        "check": {
          "title": "The check Schema",
          "type": "object",
          "default": {},
          "required": [
            "ability"
          ],
          "properties": {
            "ability": {
              "title": "The ability Schema",
              "type": "string",
              "default": "",
              "examples": [
                "str"
              ]
            }
          },
          "examples": []
        },
        "damage": {
          "title": "The damage Schema",
          "type": "array",
          "default": [],
          "items": {
            "title": "A Schema",
            "type": "object",
            "required": [
              "canCrit",
              "damageType",
              "formula",
              "name"
            ],
            "properties": {
              "canCrit": {
                "title": "The canCrit Schema",
                "type": "boolean",
                "examples": [
                  true,
                  false
                ]
              },
              "damageType": {
                "title": "The damageType Schema",
                "type": "string",
                "examples": [
                  "force",
                  "fire",
                  "acid"
                ]
              },
              "defaultSelection": {
                "title": "The defaultSelection Schema",
                "type": "boolean",
                "examples": [
                  true
                ]
              },
              "formula": {
                "title": "The formula Schema",
                "type": "string",
                "examples": [
                  "(floor((@details.level+1)/6)+1)d6",
                  "(floor((@details.level+1)/6)+1)d4",
                  "(floor((@details.level+1)/6)+1)d12",
                  "1d6"
                ]
              },
              "name": {
                "title": "The name Schema",
                "type": "string",
                "examples": [
                  "Force",
                  "Additional Force",
                  "Additional Fire",
                  "Ongoing Acid "
                ]
              }
            },
            "examples": []
          },
          "examples": []
        },
        "description": {
          "title": "The description Schema",
          "type": "string",
          "default": "",
          "examples": [
            "<p>This feature does a thing.</p>"
          ]
        },
        "duration": {
          "title": "The duration Schema",
          "type": "object",
          "default": {},
          "required": [
            "unit",
            "value"
          ],
          "properties": {
            "unit": {
              "title": "The unit Schema",
              "type": "string",
              "default": "",
              "examples": [
                "",
                "turn"
              ]
            },
            "value": {
              "title": "The value Schema",
              "type": [
				"null",
                "string",
                "integer"
              ],
              "default": "",
              "examples": [
                "",
                1
              ]
            }
          },
          "examples": []
        },
        "favorite": {
          "title": "The favorite Schema",
          "type": "boolean",
          "default": false,
          "examples": [
            false,
            true
          ]
        },
        "healing": {
          "title": "The healing Schema",
          "type": "array",
          "default": [],
          "items": {},
          "examples": []
        },
        "proficient": {
          "title": "The proficient Schema",
          "type": "boolean",
          "default": false,
          "examples": [
            true
          ]
        },
        "range": {
          "title": "The range Schema",
          "type": ["array","object"],
          "default": [],
          "items": {
            "title": "A Schema",
            "type": "string",
            "default": "",
            "examples": [
              "Within Commanding Presence range",
              "20 ft.",
              "medium"
            ]
          },
          "examples": []
        },
        "save": {
          "title": "The save Schema",
          "type": "object",
          "default": {},
          "required": [
            "dc",
            "onSave",
            "targetAbility"
          ],
          "properties": {
            "dc": {
              "title": "The dc Schema",
              "type": ["null","string"],
              "default": "",
              "examples": [
                "",
                "@spellDC"
              ]
            },
            "onSave": {
              "title": "The onSave Schema",
              "type": "string",
              "default": "",
              "examples": [
                "",
                "Half damage"
              ]
            },
            "targetAbility": {
              "title": "The targetAbility Schema",
              "type": "string",
              "default": "",
              "examples": [
                "",
                "str",
                "dex",
                "con",
                "int",
                "wis",
                "cha"
              ]
            }
          },
          "examples": []
        },
        "source": {
          "title": "The source Schema",
          "type": "string",
          "default": "",
          "examples": [
            ""
          ]
        },
        "target": {
          "title": "The target Schema",
          "type": "object",
          "default": {},
          "required": [
            "quantity",
            "type"
          ],
          "properties": {
            "quantity": {
              "title": "The quantity Schema",
              "type": [
                "null",
                "string",
                "integer"
              ],
              "default": "",
              "examples": [
                "",
                1
              ]
            },
            "type": {
              "title": "The type Schema",
              "type": "string",
              "default": "",
              "examples": [
                "",
                "creature"
              ]
            },
            "shape": {
              "title": "The shape Schema",
              "type": "string",
              "default": "",
              "examples": [
                ""
              ]
            },
            "size": {
              "title": "The size Schema",
              "type": "string",
              "default": "",
              "examples": [
                ""
              ]
            }
          },
          "examples": []
        },
        "uses": {
          "title": "The uses Schema",
          "type": "object",
          "default": {},
          "required": [
            "value",
            "max",
            "per"
          ],
          "properties": {
            "value": {
              "title": "The value Schema",
              "type": [
                "null",
                "integer"
              ],
              "default": null,
              "examples": [
                null,
                1
              ]
            },
            "max": {
              "title": "The max Schema",
              "type": [
                "null",
                "string",
                "integer"
              ],
              "default": "",
              "examples": [
                "",
                1
              ]
            },
            "per": {
              "title": "The per Schema",
              "type": [
                "null",
                "string"
              ],
              "default": null,
              "examples": [
                null,
                "longRest"
              ]
            }
          },
          "examples": []
        },
        "featureType": {
          "title": "The featureType Schema",
          "type": "string",
          "default": "",
          "examples": [
            "class"
          ]
        },
        "ammunitionProperties": {
          "title": "The ammunitionProperties Schema",
          "type": "array",
          "default": [],
          "items": {},
          "examples": []
        },
        "armorCategory": {
          "title": "The armorCategory Schema",
          "type": "string",
          "default": "",
          "examples": [
            ""
          ]
        },
        "armorProperties": {
          "title": "The armorProperties Schema",
          "type": ["array","object"],
          "default": [],
          "items": {},
          "examples": []
        },
        "attuned": {
          "title": "The attuned Schema",
          "type": "boolean",
          "default": false,
          "examples": [
            false
          ]
        },
        "bulky": {
          "title": "The bulky Schema",
          "type": "boolean",
          "default": false,
          "examples": [
            false
          ]
        },
        "equipped": {
          "title": "The equipped Schema",
          "type": "boolean",
          "default": false,
          "examples": [
            false
          ]
        },
        "materialProperties": {
          "title": "The materialProperties Schema",
          "type": ["array","object"],
          "default": [],
          "items": {},
          "examples": []
        },
        "objectType": {
          "title": "The objectType Schema",
          "type": "string",
          "default": "",
          "examples": [
            "",
            "weapon"
          ]
        },
        "plotItem": {
          "title": "The plotItem Schema",
          "type": "boolean",
          "default": false,
          "examples": [
            true,
            false
          ]
        },
        "price": {
          "title": "The price Schema",
          "type": "string",
          "default": "",
          "examples": [
            "0"
          ]
        },
        "quantity": {
          "title": "The quantity Schema",
          "type": "integer",
          "default": 0,
          "examples": [
            1
          ]
        },
        "rarity": {
          "title": "The rarity Schema",
          "type": "string",
          "default": "",
          "examples": [
            "common"
          ]
        },
        "requiresAttunement": {
          "title": "The requiresAttunement Schema",
          "type": "boolean",
          "default": false,
          "examples": [
            false,
            true
          ]
        },
        "weaponProperties": {
          "title": "The weaponProperties Schema",
          "type": ["array","object"],
          "default": [],
          "items": {},
          "examples": []
        },
        "weight": {
          "title": "The weight Schema",
          "type": "string",
          "default": "",
          "examples": [
            "0"
          ]
        }
      },
      "examples": []
    },
    "effects": {
      "title": "The effects Schema",
      "type": "array",
      "default": [],
      "items": {},
      "examples": []
    },
    "flags": {
      "title": "The flags Schema",
      "type": "object",
      "default": {},
      "required": [],
      "properties": {},
      "examples": []
    },
    "_id": {
      "title": "The _id Schema",
      "type": "string",
      "default": "",
      "examples": [
        "jg5ptsds5fgmupgr",
        "mrr8lw68g6jfntkc"
      ]
    }
  },
  "examples": []
}

=== Pjb518/FoundryVTT-Level-Up-Official/packs/classFeatures/orienteering.json
{
  "name": "Orienteering",
  "type": "feature",
  "img": "icons/svg/item-bag.svg",
  "system": {
    "ability": "",
    "actionOptions": [],
    "activation": {
      "cost": "",
      "type": "",
      "reactionTrigger": ""
    },
    "attack": {
      "bonus": "",
      "critThreshold": 20,
      "type": ""
    },
    "area": {
      "shape": ""
    },
    "check": {
      "ability": "str"
    },
    "damage": [],
    "description": "<p style=\"text-align: right\"><em>Field Discovery</em></p><hr class=\"a5e-rule u-my-md\"><p>You always know to have a bit of magnet and a pin on you for orienteering emergencies. With 1 minute’s work you can cobble together a makeshift compass. Compasses made in this way become useless after 1 hour and have no sale value. You’re also adept at surveying your surroundings and you gain an expertise die on checks made for the Chronicle journey activity. <br>In addition, you gain proficiency in Survival and its wayfinding skill specialty. If you already have this skill specialty you instead gain a Survival skill specialty of your choice. <br></p>",
    "duration": {
      "unit": "",
      "value": ""
    },
    "healing": [],
    "proficient": true,
    "range": [],
    "save": {
      "dc": "",
      "onSave": "",
      "targetAbility": ""
    },
    "source": "",
    "target": {
      "quantity": "",
      "type": ""
    },
    "uses": {
      "value": null,
      "max": "",
      "per": null
    },
    "featureType": "class"
  },
  "effects": [],
  "flags": {},
  "_id": "9tnhmj0i844q9g1d"
}

=== Pjb518/FoundryVTT-Level-Up-Official/packs/classFeatures/advantageous-action.json
{
  "name": "Advantageous Action",
  "type": "feature",
  "img": "icons/svg/item-bag.svg",
  "effects": [],
  "flags": {},
  "system": {
    "ability": "",
    "actionOptions": [],
    "activation": {
      "cost": "",
      "type": "",
      "reactionTrigger": ""
    },
    "attack": {
      "bonus": "",
      "critThreshold": 20,
      "type": ""
    },
    "area": {
      "shape": "",
      "size": ""
    },
    "check": {
      "ability": "str"
    },
    "damage": [],
    "description": "<p><span class=\"fontstyle1\"><span class=\"fontstyle0\">Starting at 14th level, your experience in battle lets you help your companions more easily. You can use the Help action as a bonus action. In addition,</span>&nbsp;<span class=\"fontstyle0\">when you take the Help action choose one of the following effects:</span></span></p>\n<ul>\n<li><span class=\"fontstyle1\">You end the frightened condition on one creature within 30 feet of you that can hear or see you.</span></li>\n<li><span class=\"fontstyle1\">You grant one creature within 5 feet of you temporary hit points equal to your Charisma modifier.</span></li>\n<li><span class=\"fontstyle1\">You touch a living creature that has 0 hit points. The creature regains 1 hit point.</span></li>\n</ul>",
    "duration": {
      "unit": "",
      "value": ""
    },
    "healing": [],
    "proficient": true,
    "range": [],
    "save": {
      "dc": "",
      "onSave": "",
      "targetAbility": ""
    },
    "source": "",
    "target": {
      "quantity": "",
      "type": "",
      "shape": "",
      "size": ""
    },
    "uses": {
      "value": null,
      "max": "",
      "per": null
    },
    "featureType": "class",
    "favorite": false
  },
  "_id": "ywoe5wghb18ujal4"
}

=== Pjb518/FoundryVTT-Level-Up-Official/packs/classFeatures/stolen-breath-(recharge-5-6).json
{
  "name": "Stolen Breath (recharge 5-6)",
  "type": "feature",
  "img": "icons/svg/item-bag.svg",
  "system": {
    "ability": "",
    "actionOptions": [
      "savingThrow",
      "damage"
    ],
    "activation": {
      "cost": 1,
      "type": "action",
      "reactionTrigger": ""
    },
    "attack": {
      "bonus": "",
      "critThreshold": 20,
      "type": ""
    },
    "area": {
      "shape": "cone",
      "length": 30
    },
    "check": {
      "ability": "str"
    },
    "damage": [
      {
        "canCrit": false,
        "damageType": "necrotic",
        "defaultSelection": true,
        "formula": "3d6",
        "name": "Necrotic"
      },
      {
        "canCrit": false,
        "damageType": "",
        "defaultSelection": true,
        "formula": "3d6",
        "name": "Original dragon breath type"
      }
    ],
    "description": "<p>The monster exhales the putrid and infected gullet of a fallen dragon in a 30-foot cone. Each creature in the area makes a Dexterity saving throw. A creature takes 3d6 necrotic damage and 3d6 damage of the type the dragon breathed in life on a failed saving throw, or half damage on a success.</p>",
    "duration": {
      "unit": "instantaneous",
      "value": ""
    },
    "healing": [],
    "proficient": true,
    "range": [],
    "save": {
      "dc": "",
      "onSave": "half damage",
      "targetAbility": "dex"
    },
    "source": "",
    "target": {
      "quantity": null,
      "type": ""
    },
    "uses": {
      "value": null,
      "max": null,
      "per": ""
    },
    "featureType": "naturalWeapon"
  },
  "effects": [],
  "flags": {
    "a5e": {
      "placeTemplate": true
    }
  },
  "_id": "js5aezx7oly5je4t"
}

=== Pjb518/FoundryVTT-Level-Up-Official/packs/classFeatures/archdruid-(fire).json
{
    "name": "Archdruid (Fire)",
    "type": "feature",
    "img": "icons/svg/item-bag.svg",
    "effects": [

    ],
    "flags": {

    },
    "system": {
        "ability": "",
        "actionOptions": [
            "damage",
            "savingThrow"
        ],
        "activation": {
            "cost": 1,
            "type": "bonusAction",
            "reactionTrigger": ""
        },
        "attack": {
            "bonus": "",
            "critThreshold": 20,
            "type": ""
        },
        "area": {
            "shape": null,
            "size": ""
        },
        "check": {
            "ability": "str"
        },
        "damage": [
            {
                "canCrit": false,
                "damageType": "fire",
                "formula": "6d6",
                "name": "Fire"
            }
        ],
        "description": "<p>You can turn nature in its rawest elements into deadly weapons no matter your form. Once each turn, you can use a bonus action to choose a target point within 30 feet and one of the following element options. If the element you choose is not present at or near the target point, any damage dealt by this feature is halved, you have disadvantage on your spell attack, and creatures have advantage on any saving throws made to resist it.</p><p style=\"text-align: start\"><strong>Fire.</strong> Flames roil outward in a burst of inferno. Creatures within 15 feet of the target point take 6d6 fire damage. A creature that makes a Dexterity saving throw against your spell save DC takes half damage.</p><p><br></p><p style=\"text-align: start\"></p>",
        "duration": {
            "unit": "",
            "value": ""
        },
        "healing": [

        ],
        "proficient": true,
        "range": [
            "15"
        ],
        "save": {
            "dc": "8+@wis.mod+@prof",
            "onSave": "Half damage",
            "targetAbility": "dex"
        },
        "source": "",
        "target": {
            "quantity": "",
            "type": ""
        },
        "uses": {
            "value": null,
            "max": "",
            "per": null
        },
        "featureType": "class",
        "favorite": false
    },
    "_id": "bn21edsk4gngf0h1"
}

=== Pjb518/FoundryVTT-Level-Up-Official/packs/classFeatures/ultimate-schema.json
{
  "name": "Ultimate Schema",
  "type": "feature",
  "img": "icons/svg/item-bag.svg",
  "system": {
    "ability": "",
    "actionOptions": [],
    "activation": {
      "cost": 1,
      "type": "action",
      "reactionTrigger": ""
    },
    "attack": {
      "bonus": "",
      "critThreshold": 20,
      "type": ""
    },
    "area": {
      "shape": ""
    },
    "check": {
      "ability": "str"
    },
    "damage": [],
    "description": "<p>At 20th level, youâ€™re clever enough to accomplish anything. Whenever you complete a long rest, choose an effect that could be accomplished by a spell of level 8 or lower. You can have that effect occur immediately, or keep it in reserve for the day, and cause it to occur at any point by spending an action. This can be because you acquired a magic item or spellcaster willing to perform the magic, or have a device or hirelings capable of matching the feat.</p>",
    "duration": {
      "unit": "",
      "value": ""
    },
    "healing": [],
    "proficient": true,
    "range": [],
    "save": {
      "dc": "",
      "onSave": "",
      "targetAbility": ""
    },
    "source": "",
    "target": {
      "quantity": "",
      "type": ""
    },
    "uses": {
      "value": 1,
      "max": 1,
      "per": "day"
    },
    "featureType": "class"
  },
  "effects": [],
  "flags": {},
  "_id": "mt8j4lz2olaw9cyg"
}
