=== Pjb518/FoundryVTT-Level-Up-Official/packs/classFeatures/_classFeaturesSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Class Features Schema",
  "type": "object",
  "default": {},
  "required": [
    "name",
    "type",
    "img",
    "system",
    "effects",
    "flags",
    "_id"
  ],
  "properties": {
    "name": {
      "title": "The name Schema",
      "type": "string",
      "default": "",
      "examples": [
        "A Better Mousetrap",
        "Advanced Grafting",
        "Ancestral Guidance"
      ]
    },
    "type": {
      "title": "The type Schema",
      "type": "string",
      "enum": [
        "feature",
        "object"
      ],
      "examples": [
        "feature",
        "object"
      ]
    },
    "img": {
      "title": "The img Schema",
      "type": "string",
      "default": [
        "icons/svg/item-bag.svg"
      ],
      "examples": [
        "icons/svg/item-bag.svg",
        "icons/weapons/thrown/grenade-round.webp",
        "icons/weapons/thrown/bomb-gas-grey-purple.webp"
      ]
    },
    "system": {
      "title": "The system Schema",
      "type": "object",
      "default": {},
      "required": [
        "ability",
        "actionOptions",
        "activation",
        "attack",
        "area",
        "check",
        "damage",
        "description",
        "duration",
        "healing",
        "proficient",
        "range",
        "save",
        "source",
        "target",
        "uses",
        "featureType"
      ],
      "properties": {
        "ability": {
          "title": "The ability Schema",
          "type": [
            "null",
            "string"
          ],
          "default": "",
          "enum": [
            null,
            "",
            "str",
            "dex",
            "con",
            "int",
            "wis",
            "cha",
            "spellcasting"
          ],
          "examples": [
            null,
            "",
            "str",
            "dex",
            "con",
            "int",
            "wis",
            "cha"
          ]
        },
        "actionOptions": {
          "title": "The actionOptions Schema",
          "type": "array",
          "default": [],
          "items": {
            "title": "A Schema",
            "type": [
              "null",
              "string"
            ],
            "default": "",
            "enum": [
              null,
              "",
              "attack",
              "bonusAction",
              "damage",
              "healing",
              "savingThrow"
            ],
            "examples": [
              "attack",
              "damage",
              "healing",
              "savingThrow"
            ]
          },
          "examples": []
        },
        "activation": {
          "title": "The activation Schema",
          "type": "object",
          "default": {},
          "required": [
            "cost",
            "type",
            "reactionTrigger"
          ],
          "properties": {
            "cost": {
              "title": "The cost Schema",
              "type": [
                "null",
                "string",
                "integer"
              ],
              "default": "",
              "examples": [
                "",
                1
              ]
            },
            "type": {
              "title": "The type Schema",
              "type": "string",
              "default": "",
              "enum": [
                "",
                "action",
                "bonusAction",
                "hour",
                "minute",
                "none",
                "reaction",
                "special"
              ],
              "examples": [
                "",
                "action",
                "special"
              ]
            },
            "reactionTrigger": {
              "title": "The reactionTrigger Schema",
              "type": "string",
              "default": "",
              "examples": [
                ""
              ]
            }
          },
          "examples": []
        },
        "attack": {
          "title": "The attack Schema",
          "type": "object",
          "default": {},
          "required": [
            "bonus",
            "critThreshold",
            "type"
          ],
          "properties": {
            "bonus": {
              "title": "The bonus Schema",
              "type": "string",
              "default": "",
              "examples": [
                ""
              ]
            },
            "critThreshold": {
              "title": "The critThreshold Schema",
              "type": [
                "integer",
                "string"
              ],
              "default": 0,
              "examples": [
                20,
                "20"
              ]
            },
            "type": {
              "title": "The type Schema",
              "type": "string",
              "default": "",
              "examples": [
                "",
                "rangedWeaponAttack"
              ]
            }
          },
          "examples": []
        },
        "area": {
          "title": "The area Schema",
          "type": "object",
          "default": {},
          "properties": {
            "shape": {
              "title": "The shape Schema",
              "type": ["null","string"],
              "default": "",
              "examples": [
                ""
              ]
            },
            "size": {
              "title": "The size Schema",
              "type": "string",
              "default": "",
              "examples": [
                ""
              ]
            }
          },
          "examples": []
        },
        "check": {
          "title": "The check Schema",
          "type": "object",
          "default": {},
          "required": [
            "ability"
          ],
          "properties": {
            "ability": {
              "title": "The ability Schema",
              "type": "string",
              "default": "",
              "examples": [
                "str"
              ]
            }
          },
          "examples": []
        },
        "damage": {
          "title": "The damage Schema",
          "type": "array",
          "default": [],
          "items": {
            "title": "A Schema",
            "type": "object",
            "required": [
              "canCrit",
              "damageType",
              "formula",
              "name"
            ],
            "properties": {
              "canCrit": {
                "title": "The canCrit Schema",
                "type": "boolean",
                "examples": [
                  true,
                  false
                ]
              },
              "damageType": {
                "title": "The damageType Schema",
                "type": "string",
                "examples": [
                  "force",
                  "fire",
                  "acid"
                ]
              },
              "defaultSelection": {
                "title": "The defaultSelection Schema",
                "type": "boolean",
                "examples": [
                  true
                ]
              },
              "formula": {
                "title": "The formula Schema",
                "type": "string",
                "examples": [
                  "(floor((@details.level+1)/6)+1)d6",
                  "(floor((@details.level+1)/6)+1)d4",
                  "(floor((@details.level+1)/6)+1)d12",
                  "1d6"
                ]
              },
              "name": {
                "title": "The name Schema",
                "type": "string",
                "examples": [
                  "Force",
                  "Additional Force",
                  "Additional Fire",
                  "Ongoing Acid "
                ]
              }
            },
            "examples": []
          },
          "examples": []
        },
        "description": {
          "title": "The description Schema",
          "type": "string",
          "default": "",
          "examples": [
            "<p>This feature does a thing.</p>"
          ]
        },
        "duration": {
          "title": "The duration Schema",
          "type": "object",
          "default": {},
          "required": [
            "unit",
            "value"
          ],
          "properties": {
            "unit": {
              "title": "The unit Schema",
              "type": "string",
              "default": "",
              "examples": [
                "",
                "turn"
              ]
            },
            "value": {
              "title": "The value Schema",
              "type": [
				"null",
                "string",
                "integer"
              ],
              "default": "",
              "examples": [
                "",
                1
              ]
            }
          },
          "examples": []
        },
        "favorite": {
          "title": "The favorite Schema",
          "type": "boolean",
          "default": false,
          "examples": [
            false,
            true
          ]
        },
        "healing": {
          "title": "The healing Schema",
          "type": "array",
          "default": [],
          "items": {},
          "examples": []
        },
        "proficient": {
          "title": "The proficient Schema",
          "type": "boolean",
          "default": false,
          "examples": [
            true
          ]
        },
        "range": {
          "title": "The range Schema",
          "type": ["array","object"],
          "default": [],
          "items": {
            "title": "A Schema",
            "type": "string",
            "default": "",
            "examples": [
              "Within Commanding Presence range",
              "20 ft.",
              "medium"
            ]
          },
          "examples": []
        },
        "save": {
          "title": "The save Schema",
          "type": "object",
          "default": {},
          "required": [
            "dc",
            "onSave",
            "targetAbility"
          ],
          "properties": {
            "dc": {
              "title": "The dc Schema",
              "type": ["null","string"],
              "default": "",
              "examples": [
                "",
                "@spellDC"
              ]
            },
            "onSave": {
              "title": "The onSave Schema",
              "type": "string",
              "default": "",
              "examples": [
                "",
                "Half damage"
              ]
            },
            "targetAbility": {
              "title": "The targetAbility Schema",
              "type": "string",
              "default": "",
              "examples": [
                "",
                "str",
                "dex",
                "con",
                "int",
                "wis",
                "cha"
              ]
            }
          },
          "examples": []
        },
        "source": {
          "title": "The source Schema",
          "type": "string",
          "default": "",
          "examples": [
            ""
          ]
        },
        "target": {
          "title": "The target Schema",
          "type": "object",
          "default": {},
          "required": [
            "quantity",
            "type"
          ],
          "properties": {
            "quantity": {
              "title": "The quantity Schema",
              "type": [
                "null",
                "string",
                "integer"
              ],
              "default": "",
              "examples": [
                "",
                1
              ]
            },
            "type": {
              "title": "The type Schema",
              "type": "string",
              "default": "",
              "examples": [
                "",
                "creature"
              ]
            },
            "shape": {
              "title": "The shape Schema",
              "type": "string",
              "default": "",
              "examples": [
                ""
              ]
            },
            "size": {
              "title": "The size Schema",
              "type": "string",
              "default": "",
              "examples": [
                ""
              ]
            }
          },
          "examples": []
        },
        "uses": {
          "title": "The uses Schema",
          "type": "object",
          "default": {},
          "required": [
            "value",
            "max",
            "per"
          ],
          "properties": {
            "value": {
              "title": "The value Schema",
              "type": [
                "null",
                "integer"
              ],
              "default": null,
              "examples": [
                null,
                1
              ]
            },
            "max": {
              "title": "The max Schema",
              "type": [
                "null",
                "string",
                "integer"
              ],
              "default": "",
              "examples": [
                "",
                1
              ]
            },
            "per": {
              "title": "The per Schema",
              "type": [
                "null",
                "string"
              ],
              "default": null,
              "examples": [
                null,
                "longRest"
              ]
            }
          },
          "examples": []
        },
        "featureType": {
          "title": "The featureType Schema",
          "type": "string",
          "default": "",
          "examples": [
            "class"
          ]
        },
        "ammunitionProperties": {
          "title": "The ammunitionProperties Schema",
          "type": "array",
          "default": [],
          "items": {},
          "examples": []
        },
        "armorCategory": {
          "title": "The armorCategory Schema",
          "type": "string",
          "default": "",
          "examples": [
            ""
          ]
        },
        "armorProperties": {
          "title": "The armorProperties Schema",
          "type": ["array","object"],
          "default": [],
          "items": {},
          "examples": []
        },
        "attuned": {
          "title": "The attuned Schema",
          "type": "boolean",
          "default": false,
          "examples": [
            false
          ]
        },
        "bulky": {
          "title": "The bulky Schema",
          "type": "boolean",
          "default": false,
          "examples": [
            false
          ]
        },
        "equipped": {
          "title": "The equipped Schema",
          "type": "boolean",
          "default": false,
          "examples": [
            false
          ]
        },
        "materialProperties": {
          "title": "The materialProperties Schema",
          "type": ["array","object"],
          "default": [],
          "items": {},
          "examples": []
        },
        "objectType": {
          "title": "The objectType Schema",
          "type": "string",
          "default": "",
          "examples": [
            "",
            "weapon"
          ]
        },
        "plotItem": {
          "title": "The plotItem Schema",
          "type": "boolean",
          "default": false,
          "examples": [
            true,
            false
          ]
        },
        "price": {
          "title": "The price Schema",
          "type": "string",
          "default": "",
          "examples": [
            "0"
          ]
        },
        "quantity": {
          "title": "The quantity Schema",
          "type": "integer",
          "default": 0,
          "examples": [
            1
          ]
        },
        "rarity": {
          "title": "The rarity Schema",
          "type": "string",
          "default": "",
          "examples": [
            "common"
          ]
        },
        "requiresAttunement": {
          "title": "The requiresAttunement Schema",
          "type": "boolean",
          "default": false,
          "examples": [
            false,
            true
          ]
        },
        "weaponProperties": {
          "title": "The weaponProperties Schema",
          "type": ["array","object"],
          "default": [],
          "items": {},
          "examples": []
        },
        "weight": {
          "title": "The weight Schema",
          "type": "string",
          "default": "",
          "examples": [
            "0"
          ]
        }
      },
      "examples": []
    },
    "effects": {
      "title": "The effects Schema",
      "type": "array",
      "default": [],
      "items": {},
      "examples": []
    },
    "flags": {
      "title": "The flags Schema",
      "type": "object",
      "default": {},
      "required": [],
      "properties": {},
      "examples": []
    },
    "_id": {
      "title": "The _id Schema",
      "type": "string",
      "default": "",
      "examples": [
        "jg5ptsds5fgmupgr",
        "mrr8lw68g6jfntkc"
      ]
    }
  },
  "examples": []
}

=== Pjb518/FoundryVTT-Level-Up-Official/packs/classFeatures/style_-great-weapon-fighting.json
{
	"name": "Style: Great Weapon Fighting",
	"type": "feature",
	"img": "icons/svg/item-bag.svg",
	"effects": [],
	"flags": {},
	"system": {
		"ability": "",
		"actionOptions": [],
		"activation": {
			"cost": "",
			"type": "",
			"reactionTrigger": ""
		},
		"attack": {
			"bonus": "",
			"critThreshold": 20,
			"type": ""
		},
		"area": {
			"shape": "",
			"size": ""
		},
		"check": {
			"ability": "str"
		},
		"damage": [],
		"description": "<p>When you roll a 1 or 2 on a damage die for an attack you make with a melee weapon that you are wielding with two hands, you can reroll the die and must use the new roll, even if the new roll is a 1 or a 2. The weapon must have the two-handed or versatile property for you to gain this benefit.</p>",
		"duration": {
			"unit": "",
			"value": ""
		},
		"healing": [],
		"proficient": true,
		"range": [],
		"save": {
			"dc": "",
			"onSave": "",
			"targetAbility": ""
		},
		"source": "",
		"target": {
			"quantity": "",
			"type": ""
		},
		"uses": {
			"value": null,
			"max": "",
			"per": null
		},
		"featureType": "class"
	},
	"_id": "jxm6j7msf0qxfsnw"
}

=== Pjb518/FoundryVTT-Level-Up-Official/packs/classFeatures/bonus-proficiencies-(engineer).json
{
  "name": "Bonus Proficiencies (Engineer)",
  "type": "feature",
  "img": "icons/svg/item-bag.svg",
  "system": {
    "ability": "",
    "actionOptions": [],
    "activation": {
      "cost": "",
      "type": "",
      "reactionTrigger": ""
    },
    "attack": {
      "bonus": "",
      "critThreshold": 20,
      "type": ""
    },
    "area": {
      "shape": ""
    },
    "check": {
      "ability": "str"
    },
    "damage": [],
    "description": "<p>When you select this archetype at 3rd level, you gain proficiency with air vehicles, land vehicles, and water vehicles. If you already had any of these proficiencies you gain an expertise die with that type of vehicle instead. </p>",
    "duration": {
      "unit": "",
      "value": ""
    },
    "healing": [],
    "proficient": true,
    "range": [],
    "save": {
      "dc": "",
      "onSave": "",
      "targetAbility": ""
    },
    "source": "",
    "target": {
      "quantity": "",
      "type": ""
    },
    "uses": {
      "value": null,
      "max": "",
      "per": null
    },
    "featureType": "class"
  },
  "effects": [],
  "flags": {},
  "_id": "9epwhm8pz2wpni0v"
}

=== Pjb518/FoundryVTT-Level-Up-Official/packs/synergyFeats/true-revenant.json
{
	"name": "True Revenant",
	"type": "feature",
	"img": "icons/svg/item-bag.svg",
	"effects": [],
	"flags": {
		"core": {
			"sourceId": "Compendium.a5e.a5e-synergy-feats.hkw7727vrhldbqod"
		}
	},
	"system": {
		"ability": "",
		"actionOptions": [],
		"actions": {},
		"activation": {
			"cost": "",
			"type": "",
			"reactionTrigger": ""
		},
		"attack": {
			"bonus": "",
			"critThreshold": 20,
			"type": ""
		},
		"area": {
			"shape": ""
		},
		"check": {
			"ability": "str"
		},
		"damage": [],
		"description": "<p><strong><em>Prerequisites</em></strong><em>: Revenant feat</em></p><p>Even though it has carried you beyond the mortal pale and back again, your mission has become do or die as you exchange the last vestiges of your soul for more power so that you can finally destroy your foes. One year and one day after you select this feat or when your vendetta has ended, you are doomed. Until then, you gain the following benefits:</p><ul><li><p>You cannot be charmed, fatigued, frightened, paralyzed, or stunned.</p></li><li><p>You have advantage on saving throws against spells and other magical effects.</p></li><li><p>You regain all of your hit points after you do not take any damage for 1 minute.</p></li></ul><p>In addition, you also gain the Fearsome Pursuit and Burning Hatred features.</p><p><strong><em>Fearsome Pursuit.</em> </strong>You can spend 1 minute focusing on a creature that is part of your vendetta. If the creature is dead or on another plane of existence, you learn that. Otherwise, after focusing, you know the distance and direction to that creature, and so long as you’re moving in pursuit of that creature, you and anyone traveling with you ignore difficult terrain. This effect ends if you take damage or end your turn without moving for any reason.</p><p><strong><em>Burning Hatred.</em> </strong>You can use an action to target the focus of your Fearsome Pursuit if it is within 30 feet. The creature makes a Wisdom saving throw (DC 8 + your proficiency bonus + your highest mental ability score modifier). On a failure, it takes psychic damage equal to 1d6 × your proficiency bonus and is stunned until the end of its next turn. On a success, it takes half damage and is rattled until the end of its next turn. Once you have used this feature a number of times equal to your proficiency bonus, you can’t use it again until you finish a long rest.</p>",
		"duration": {
			"unit": "",
			"value": ""
		},
		"favorite": false,
		"healing": [],
		"proficient": true,
		"range": [],
		"save": {
			"dc": "",
			"onSave": "",
			"targetAbility": ""
		},
		"secretDescription": "",
		"source": "",
		"target": {
			"quantity": "",
			"type": ""
		},
		"uses": {
			"value": null,
			"max": "",
			"per": null
		},
		"featureType": "feat",
		"prerequisite": ""
	},
	"_id": "hkw7727vrhldbqod"
}

=== Pjb518/FoundryVTT-Level-Up-Official/packs/classFeatures/font-of-magic.json
{
  "name": "Font of Magic",
  "type": "feature",
  "img": "icons/svg/item-bag.svg",
  "system": {
    "ability": "",
    "actionOptions": [],
    "activation": {
      "cost": "",
      "type": "",
      "reactionTrigger": ""
    },
    "attack": {
      "bonus": "",
      "critThreshold": 20,
      "type": ""
    },
    "area": {
      "shape": ""
    },
    "check": {
      "ability": "str"
    },
    "damage": [],
    "description": "<p>At 2nd level, you’ve begun to understand the well of power within you that you draw from to cast your magics. Up until now, it’s just been something abstract, maybe hardly understood, but now you can use it in a precise manner to fuel your magics. It grants you a new resource in the form of Sorcery Points, as well as a way to use them.</p><h3 style=\"text-align: start\">Sorcery Points</h3><p style=\"text-align: start\">You have 2 Sorcery Points, and you gain more as you reach higher levels, as shown in the Sorcery Points column of the Sorcerer table. You can never have more Sorcery Points than shown on the table for your level. You regain all spent Sorcery Points when you finish a long rest.</p><h3 style=\"text-align: start\">Flexible Casting</h3><p style=\"text-align: start\">You can use your Sorcery Points to gain additional spell slots, or sacrifice spell slots to gain additional Sorcery Points.&nbsp;</p><p style=\"text-align: start\"><strong>Conversion. </strong>You can transform unexpended Sorcery Points into one spell slot, or vice versa, as a bonus action. The Creating Spell Slots table shows the cost of creating a spell slot of a given level, or the value of sacrificing a spell slot for Sorcery Points.&nbsp;You cannot convert spells of 6th-level or higher.</p>",
    "duration": {
      "unit": "",
      "value": ""
    },
    "healing": [],
    "proficient": true,
    "range": [],
    "save": {
      "dc": "",
      "onSave": "",
      "targetAbility": ""
    },
    "source": "",
    "target": {
      "quantity": "",
      "type": ""
    },
    "uses": {
      "value": null,
      "max": "",
      "per": null
    },
    "featureType": "class"
  },
  "effects": [],
  "flags": {},
  "_id": "8lf349fflv8456yj"
}

=== Pjb518/FoundryVTT-Level-Up-Official/packs/classFeatures/toll_-one-eye-open.json
{
	"name": "Toll: One Eye Open",
	"type": "feature",
	"img": "icons/svg/item-bag.svg",
	"effects": [],
	"flags": {
		"core": {
			"sourceId": "Compendium.a5e.a5e-class-features.yu0rlk1kdngglbbn"
		}
	},
	"system": {
		"actions": {},
		"description": "<p>Your life has been so regularly in danger that youâ€™ve learned to literally sleep with one eye open. You are alert and aware of your surroundings while sleeping during long rests. You can also never be surprised and you gain an expertise die on initiative checks.</p>",
		"favorite": false,
		"secretDescription": "",
		"source": "",
		"uses": {
			"value": null,
			"max": "",
			"per": null,
			"recharge": {
				"formula": "1d6",
				"threshold": 6
			}
		},
		"schema": {
			"version": 0.003,
			"lastMigration": {
				"version": {
					"schema": null,
					"foundry": "10.291",
					"system": "0.10.7"
				}
			}
		},
		"featureType": "class",
		"prerequisite": "",
		"ability": "",
		"actionOptions": [],
		"activation": {
			"cost": "",
			"type": "",
			"reactionTrigger": ""
		},
		"attack": {
			"bonus": "",
			"critThreshold": 20,
			"type": ""
		},
		"area": {
			"shape": "",
			"size": ""
		},
		"check": {
			"ability": "str"
		},
		"damage": [],
		"duration": {
			"unit": "",
			"value": ""
		},
		"healing": [],
		"proficient": true,
		"range": [],
		"save": {
			"dc": "",
			"onSave": "",
			"targetAbility": ""
		},
		"target": {
			"quantity": "",
			"type": ""
		}
	},
	"_id": "yu0rlk1kdngglbbn"
}

=== Pjb518/FoundryVTT-Level-Up-Official/packs/classFeatures/clever-scheme_-deductive-tracker.json
{
  "name": "Clever Scheme: Deductive Tracker",
  "type": "feature",
  "img": "icons/svg/item-bag.svg",
  "system": {
    "ability": "",
    "actionOptions": [],
    "activation": {
      "cost": 1,
      "type": "minute",
      "reactionTrigger": ""
    },
    "attack": {
      "bonus": "",
      "critThreshold": 20,
      "type": ""
    },
    "area": {
      "shape": ""
    },
    "check": {
      "ability": "str"
    },
    "damage": [],
    "description": "<p>After observing a creature, however briefly, you make a deduction that gives you an edge when pursuing it. After you spend at least 1 minute observing a creature, you gain an expertise die on checks made to track that specific creature.</p>",
    "duration": {
      "unit": "special",
      "value": ""
    },
    "healing": [],
    "proficient": true,
    "range": [],
    "save": {
      "dc": "",
      "onSave": "",
      "targetAbility": ""
    },
    "source": "",
    "target": {
      "quantity": "",
      "type": ""
    },
    "uses": {
      "value": null,
      "max": null,
      "per": ""
    },
    "featureType": "class"
  },
  "effects": [],
  "flags": {},
  "_id": "39x916chada5lupd"
}

=== Pjb518/FoundryVTT-Level-Up-Official/packs/classFeatures/clever-scheme_-reserved-seating.json
{
  "name": "Clever Scheme: Reserved Seating",
  "type": "feature",
  "img": "icons/svg/item-bag.svg",
  "system": {
    "ability": "",
    "actionOptions": [],
    "activation": {
      "cost": "",
      "type": "",
      "reactionTrigger": ""
    },
    "attack": {
      "bonus": "",
      "critThreshold": 20,
      "type": ""
    },
    "area": {
      "shape": ""
    },
    "check": {
      "ability": "str"
    },
    "damage": [],
    "description": "<p>You have forethought of when and where you might need to be places. If you knew you would be in a given area, once per day you can call upon this forethought to have a vehicle or mount waiting for you and your companions, or to have a reservation available at a venue. You pay any appropriate costs. For exceptional requests, you may need to make a Persuasion check or owe someone a favor.</p>",
    "duration": {
      "unit": "",
      "value": ""
    },
    "healing": [],
    "proficient": true,
    "range": [],
    "save": {
      "dc": "",
      "onSave": "",
      "targetAbility": ""
    },
    "source": "",
    "target": {
      "quantity": "",
      "type": ""
    },
    "uses": {
      "value": 1,
      "max": 1,
      "per": "day"
    },
    "featureType": "class"
  },
  "effects": [],
  "flags": {},
  "_id": "g6el4zyuuf3r10hi"
}
